---
version: '3'

tasks:
  default:
    desc: Update F5XC ip addresses
    aliases:
      - update
    cmds:
      - ./update_ips.sh
      - tofu fmt

  clean:
    desc: Remove Terraform state and plan files
    cmds:
      - rm -f *.tfstate{,.backup}
      - rm -f *.tfplan

  deep-clean:
    desc: Remove Terraform plugin/state directory
    deps:
      - clean
    cmds:
      - rm -rf .terraform
      - rm -f .terraform.lock.hcl

  dot-env:
    desc: generate .env.sample file
    cmds:
      - sed -E "s%(=\"[^$].*\"|=\\$.*)%=\"\"%" <<<$(grep -v "^#" .envrc) | tee .env.example

  template:
    desc: generate terraform.tfvars.tmpl.example file
    cmds:
      - sed -E "s%(=\s+\"[^$].*\"|=\\$.*)%= \"\"%" terraform.tfvars.tmpl | tee terraform.tfvars.tmpl.example

  user-data:
    desc: extract user-data to less
    cmds:
      - tofu output -raw user_data | base64 -d | gunzip | bat
