#cloud-config

apt:
  preserve_sources_list: false
  primary:
    - arches:
      - amd64
      uri: "http://ossmirror.mycloud.services/os/linux/ubuntu/"

  security:
    - arches:
      - amd64
      uri: "http://security.ubuntu.com/ubuntu"

packages:
 - apt-transport-https
 - podman
 - podman-compose
 - systemd-container
 # - ec2-instance-connect


package_update: true

package_upgrade: true

mount_default_fields: [ None, None, "auto", "defaults,nobootwait", "0", "2" ]

locale: en_SG.UTF-8

locale_configfile: /etc/default/locale

resize_rootfs: true

final_message: "The system is finally up, after $UPTIME seconds"

timezone: Asia/Singapore

ntp:
  enabled: true

ssh_deletekeys: True

ssh_genkeytypes: ['rsa', 'ecdsa', 'ed25519']

ssh_fp_console_blacklist: [ed25519]
ssh_key_console_blacklist: [ssh-dss]

runcmd:
 - apt-get -y purge nano
 - apt-get -y autoremove
 - cat /lib/systemd/system/ssh.service.d/ec2-instance-connect.conf
